name: Movie Night
favicon: null
layout_spectrum: 0.00211
typography_spectrum: 0.49789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e8db'
    - '#e5e015'
    - '#191410'
    - '#e49900'
    - '#888478'
  brandStrength: 0.625
  lightness: 0.8744864270556718
  saturation: 0.09569592005573213
  rhythmicContrast: 0.4928138954564929
purpose: []
